### PR TITLE
Remove variable assignments that are never used

### PR DESCRIPTION
**Pull request by kjsanger**

### CODE REVIEW

**Comment by mgcam** [comment]
This pr is not quite what is written on the tin. While I agree with some of the deletions, others are for cases when variables get assigned before, for example,  a try-except clause, whithin which the same variable is assigned. While dropping the original assignment does not break the code, it makes the code less readable and more vulnurable to future alterations. Consider, for example, a case when the except clause does not end with raising an error.

**Comment by kjsanger** [comment]
They are indeed never used - I have checked each one again. I made these changes because they are flagging up in linters as redundant and making it harder to see other issues.

**Comment by nerdstrike** [comment]
Ultimately this was my Perl brain expecting variable scope to be confined more tightly than it is. Python scopes variables to the function/class/module, so these changes are technically correct, and certainly an education for me. I'm struggling to find anything authoritative on whether to pre-assign a variable before an if/try.

@kjsanger - pylance doesn't flag these up (and misses the unused assignment in the test, because of variable reuse). Can you link me to whatever policy pycharm is applying for these?

**Comment by kjsanger** [comment]
> Can you link me to whatever policy pycharm is applying for these?

I don't think I can as it's built-in. They're only weak warnings, though. That differentiates them from things that will cause an error e.g. unbound

**Pull request merged**
